[tool.poetry]
name = "stock"
version = "0.1.0"
description = ""
authors = ["Kitamura <ymyk6602@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.27.1"
bs4 = "^0.0.1"
pydantic = "^1.9.0"
SQLAlchemy = "^1.4.40"
fake-useragent = "^0.1.11"
lxml = "^4.9.1"
pandas = "^1.4.3"
matplotlib = "^3.5.3"
fastapi = "^0.83.0"
sentry-sdk = "^1.9.5"
fastapi-utils = "^0.2.1"
uvicorn = {extras = ["standard"], version = "^0.18.3"}

[tool.poetry.dev-dependencies]
ipykernel = "^6.15.1"
ipython = "^8.4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
venvPath = ".venv"

[tool.black]
line-length = 100

[tool.flake8]
max-complexity = 10
max-line-length = 105
indent-size = 4