[tool.poetry]
name = "stock"
version = "0.1.0"
description = ""
authors = ["Kitamura <ymyk6602@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10,<3.13"
requests = "^2.31.0"
bs4 = "^0.0.2"
pydantic = "^2.6.3"
matplotlib = "^3.8.3"
selenium = "^4.18.1"
lxml = "^5.1.0"
yfinance = "^0.2.37"
requests-cache = "^1.2.0"
requests-ratelimiter = "^0.6.0"
jinja2 = "^3.1.3"
fake-useragent = "^1.4.0"
openpyxl = "^3.1.2"
xlrd = "^2.0.1"
requests-html = "^0.10.0"
polars = "^0.20.18"
plotly = "^5.22.0"
#tensorflow = "^2.17.0"
opencv-python = "^4.10.0.84"
xlwings = "^0.32.1"
pandas = "^2.2.2"
tensortrade = "^1.0.3"
ray = {extras = ["default", "rllib", "tune"], version = "^2.34.0"}
symfit = "^0.5.6"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.3"
ipython = "^8.22.2"
flake8 = "^7.0.0"
pytest = "^8.0.2"
nbstripout = "^0.7.1"
ipywidgets = "^8.1.2"
epc = "^0.0.5"
orjson = "^3.9.15"
sexpdata = "^1.0.2"
six = "^1.16.0"
setuptools = "^69.2.0"
paramiko = "^3.4.0"
rapidfuzz = "^3.6.2"
# gnn = {path = "../gnn_dev", develop = true}
#gnn = {path = "../gnn_dev"}
black = "^24.4.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

# [tool.pyright]
# venvPath = ".venv"

[tool.basedpyright]
exclude = ["data/"]
venvPath = ".venv"

[tool.black]
line-length = 100

[tool.flake8]
max-complexity = 10
max-line-length = 105
indent-size = 4

[tool.isort]
known_local_folder = ["stock", "gnn"]