[tool.poetry]
name = "stock"
version = "0.1.0"
description = ""
authors = ["Kitamura <ymyk6602@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8,<3.12"
requests = "^2.27.1"
bs4 = "^0.0.1"
pydantic = "^1.9.0"
matplotlib = "^3.5.3"
selenium = "^4.8.0"
lxml = "^4.9.3"
yfinance = "^0.2.26"
requests-cache = "^1.1.0"
requests-ratelimiter = "^0.4.1"
jinja2 = "^3.1.2"
fake-useragent = "^1.2.1"

[tool.poetry.dev-dependencies]
ipykernel = "^6.15.1"
ipython = "^8.4.0"
flake8 = "^5.0.4"
pytest = "^7.1.2"
nbstripout = "^0.6.1"
ipywidgets = "^8.0.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
venvPath = ".venv"

[tool.black]
line-length = 100

[tool.flake8]
max-complexity = 10
max-line-length = 105
indent-size = 4

[tool.isort]
skip = ["stock"]