[tool.poetry]
name = "stock"
version = "0.1.0"
description = ""
authors = ["Kitamura <ymyk6602@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8,<3.12"
requests = "^2.27.1"
bs4 = "^0.0.1"
pydantic = "^1.9.0"
SQLAlchemy = "^1.4.40"
fake-useragent = "^1.1.0"
lxml = "^4.9.1"
pandas = "^1.4.3"
matplotlib = "^3.5.3"
fastapi = "^0.92.0"
sentry-sdk = "^1.9.5"
fastapi-utils = "^0.2.1"
uvicorn = {extras = ["standard"], version = "^0.20.0"}
google-api-python-client = "^2.58.0"
google-auth-httplib2 = "^0.1.0"
seaborn = "^0.12.1"
boto3 = "^1.26.13"
tqdm = "^4.64.1"
tensorflow = {version = "^2.11.0", platform = "linux"}
tensorflow-probability = {version = "^0.19.0", platform = "linux"}
xlwings = "^0.29.1"
plotly = "^5.13.0"
requests-html = "^0.10.0"
selenium = "^4.8.0"

[tool.poetry.dev-dependencies]
ipykernel = "^6.15.1"
ipython = "^8.4.0"
flake8 = "^5.0.4"
pytest = "^7.1.2"
nbstripout = "^0.6.1"
ipywidgets = "^8.0.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
venvPath = ".venv"

[tool.black]
line-length = 100

[tool.flake8]
max-complexity = 10
max-line-length = 105
indent-size = 4