version: '3'

services:
  jupyter_lab:
    hostname: stock_dev
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        user: ${UESR}
        uid: ${USER_ID}
        gid: ${GROUP_ID}
    ports:
      - "22222:22" # for ssh
      - "5050:5000" # for many objectives
    volumes:
      - /etc/passwd:/etc/passwd
      - /etc/shadow:/etc/shadow
      - /etc/group:/etc/group
      - ../:${HOME}/work/stock
      - ./.jupyter:${HOME}/.jupyter
    environment:
      USER_NAME: ${USER}
    entrypoint: ${HOME}/work/stock/docker/entrypoint.sh
    restart: always
