version: '3'

services:
  chrome_driver:
    image: selenium/standalone-chrome:latest
    ports:
      - "4545:4444" #
    restart: always

  stock_dev:
    hostname: stock_dev
    build:
      context: ..
      dockerfile: docker/Dockerfile
      shm_size: "2g"
      args:
        user: ${UESR}
        uid: ${USER_ID}
        gid: ${GROUP_ID}
    ports:
      - "22222:22" # for ssh
      - "5050:5000" # for many objectives
    volumes:
      - /etc/passwd:/etc/passwd
      - /etc/shadow:/etc/shadow
      - /etc/group:/etc/group
      - ../:${HOME}/work/Projects/stock
      - ./.jupyter:${HOME}/.jupyter
      - ${HOME}/.ssh:${HOME}/.ssh
    environment:
      USER_NAME: ${USER}
    entrypoint: ${HOME}/work/Projects/stock/docker/entrypoint.sh
    restart: always
