version: '3'

services:
  stock_dev:
    hostname: stock_dev
    build:
      context: ..
      dockerfile: docker/Dockerfile.dl
      args:
        user: ${UESR}
        uid: ${USER_ID}
        gid: ${GROUP_ID}
    ports:
      - "22223:22" # for ssh
    volumes:
      - /etc/passwd:/etc/passwd
      - /etc/shadow:/etc/shadow
      - /etc/group:/etc/group
      - ../:${HOME}/work/stock
      - ${HOME}/.ssh:${HOME}/.ssh
    environment:
      USER_NAME: ${USER}
      PROJECT_ROOT: ${HOME}/work/stock
    entrypoint: ${HOME}/work/stock/docker/entrypoint.dl.sh
    restart: always
