version: '3'

services:
  # stock_dev:
  #   hostname: stock_dev
  #   build:
  #     context: ..
  #     dockerfile: docker/Dockerfile
  #     shm_size: "2g"
  #     args:
  #       user: ${UESR}
  #       uid: ${USER_ID}
  #       gid: ${GROUP_ID}
  #   ports:
  #     - "22222:22" # for ssh
  #     - "5050:5000" # for many objectives
  #   volumes:
  #     - /etc/passwd:/etc/passwd
  #     - /etc/shadow:/etc/shadow
  #     - /etc/group:/etc/group
  #     - ../:${HOME}/work/stock
  #     - ./.jupyter:${HOME}/.jupyter
  #     - ${HOME}/.ssh:${HOME}/.ssh
  #   environment:
  #     USER_NAME: ${USER}
  #     PROJECT_ROOT: ${HOME}/work/stock
  #   entrypoint: ${HOME}/work/stock/docker/entrypoint.sh
  #   restart: always
  # pptr_server:
  #   build:
  #     context: ..
  #     dockerfile: docker/Dockerfile.pptr
  #   ports:
  #     - "22222:22"
  #   volumes:
  #     - ../:${HOME}/work/stock
  #   environment:
  #     USER_NAME: ${USER}
  #     PROJECT_ROOT: ${HOME}/work/stock
  #   entrypoint: /sbin/sshd -D
  #   restart: always

  selenium_server:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
      - "7900:7900"
    volumes:
      - /dev/shm:/dev/shm
    restart: always
