name: Update Stock Data

on:
  workflow_dispatch:
  schedule:
    - cron: '17 22 * * *'

jobs:
  build:
    name: Run
    uses: ./.github/workflows/python-package.yml
    steps:
    - name: Run
      run: poetry run python scripts/daily_update.py
