name: Update Stock Data

on:
  workflow_dispatch:
  schedule:
    - cron: '17 22 * * *'

jobs:
  build:
    name: Build
    uses: ./.github/workflows/python-package.yml
  update:
    runs-on: ubuntu-latest
    name: Fetch and update
    needs: build
    steps:
    - name: Run
      run: poetry run python scripts/daily_update.py
