name: Update Stock Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.2.2"]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      uses: ./.github/actions/install_deps
    - name: Run
      run: poetry run python scripts/daily_update.py
