name: Update Stock Data

on:
  workflow_dispatch:
  schedule:
    - cron: '17 22 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        poetry-version: ["1.2.2"]
    steps:
    - name: Build
      uses: ./.github/actions/install_deps
    - name: Run
      run: poetry run python scripts/daily_update.py
