name: Update Japanese Stock Data

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 8 * * *'

# env:
#   AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
#   AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      uses: ./.github/actions/install_deps
    - name: Run
      run: |
        python scripts/update_code_list_jp.py
        python scripts/update_stock_data_jp.py
        python scripts/update_financial_data_jp.py
        python scripts/divide_stocks_jp.py
        # poetry run python scripts/update_watch_list_jp.py
        # poetry run python scripts/create_watch_list_jp_html.py
    - name: Diff
      id: diff
      run: |
        git pull
        git add -N .
        git diff --name-only --exit-code
      continue-on-error: true
    - name: Commit & Push
      run: |
        set -x
        git config user.name github-actions[bot]
        git config user.email stock@noreply.github.com
        git add .
        git commit --author=. -m 'update data'
        git push
      if: steps.diff.outcome == 'failure'
